#!/usr/bin/env sh

# This script is intended to be used on a Debian or Debian-based distribution
# and installs a minimal VSCode work environment with some useful extensions.




### Functions
#############

sudo_privileges() {
    id -Gn 2>/dev/null | grep -qw "sudo"
}
# ---
ask_user() {
    printf "%s\n" "$1"
    local ANS
    read -r -p "wish to proceed anyway? [y/N] " ANS
    case "$ANS" in
        y | Y | yes | YES) printf "\n%s\n" "setup resumed";;
        *) printf "\n%s\n" "setup interrupted"; exit 1;;
    esac
}
# ---
try_run() {
    if "$@" >/dev/null 2>&1; then
        printf "\n"
    else
        printf ": %s\n" "command failed"
    fi
}




### Checks
##########

if [ "$(id -u)" -eq 0 ]; then
    printf "\n%s"   "This script MUST NOT be run as root since it makes changes to"
    printf "\n%s"   "the \$HOME directory of the \$USER executing it."
    printf "\n%s"   "Run this script as a normal user, you will be asked for a sudo"
    printf "\n%s\n" "password when necessary."
    exit 1
fi
# ---
if ! command -v code >/dev/null 2>&1; then
    printf "\n%s"   "WARNING. VSCode not found: install VSCode and run this script"
    printf "\n%s\n" "═══════  again."
    exit 1
fi




### COBE-Code
#############

cat << EOF

             __                               __
.----.-----.|  |--.-----.      .----.-----.--|  |.-----.
|  __|  _  ||  _  |  -__|      |  __|  _  |  _  ||  -__|
|____|_____||_____|_____| ____ |____|_____|_____||_____|

EOF




### Packages
############

PACKAGES="git gnome-keyring fonts-cascadia-code libyaml-tiny-perl libfile-homedir-perl \
dash bash pandoc texlive-full python3-full python3-pip python3-dev black python-is-python3"

for PKG in $PACKAGES; do
    if ! apt-get -s install "$PKG" >/dev/null 2>&1; then
        PROBLEMS="${PROBLEMS:+$PROBLEMS }$PKG"
    fi
done
# ---
if [ -n "${PROBLEMS-}" ]; then
    ask_user "these packages might cause issues: '$PROBLEMS'"
fi
# ---
if ! sudo_privileges; then
    ask_user "'$USER' does not have sudo privileges"
fi




### Dependencies
################

if sudo_privileges; then
    sudo sh -c '
        apt-get update &&
        apt-get upgrade -qq -y --allow-downgrades &&
        for PKG in "$@"; do
            apt-get install -y -qq --no-install-recommends "$PKG" || true
        done
        apt-get -qq -y autoremove --purge &&
        apt-get -qq -y autoclean
    ' _ $PACKAGES || {
        printf "\n%s\n" "packages installation failed"
        exit 1
    }
fi




### Start
#########

printf "\n%s\n" "UNINSTALLING ALL EXTENSIONS"
for EXTENSION in $(\code --list-extensions); do
    printf "%s" "uninstalling '$EXTENSION'"
    try_run \code --uninstall-extension "$EXTENSION"
done
rm -rf "$HOME/.config/Code/CachedExtensionVSIXs" \
      "$HOME/.vscode/extensions" 2>/dev/null || true
# ---
printf "\n%s\n" "INSTALLING CODE EXTENSIONS"
for EXTENSION in \
    github.copilot-chat \
    openai.chatgpt \
    monokai.theme-monokai-pro-vscode \
    james-yu.latex-workshop \
    ms-python.python \
    ms-python.black-formatter \
    ms-toolsai.jupyter \
    ms-toolsai.datawrangler \
    ms-vscode-remote.remote-ssh
do
    printf "%s" "installing '$EXTENSION'"
    try_run \code --install-extension "$EXTENSION"
done
# ---
BASE="$HOME/.config/Code/User"
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
if mkdir -p "$BASE"; then
    cat "$SCRIPTPATH/code/settings.json" > "$BASE/settings.json"
    cat "$SCRIPTPATH/code/keybindings.json" > "$BASE/keybindings.json"
fi




### Finish
##########

printf "\n%s\n" "CODE SETUP COMPLETE."
