#!/usr/bin/env sh
set -eu




### Functions
#############

run_installer() {
    [ -f "$1" ] || {
        printf "%s\n" "WARNING. '$1' not found."
        exit 1
    }
    chmod +x "$1" 2>/dev/null || :
    "$1"
}




### COBE-Install
################

cat << EOF

This script installs COBE (the "COde Base Environment") on your
system. It will run just one installer: cobe_code.
╔═════════╗
║cobe_code║ Installs all the basic packages you need and resets your
╚═════════╝ VSCode configuration, plus it installs few extensions to
            make it as loose as a goose and ready to roll in no time.

EOF




### Code
########

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)
CODE_INSTALLER="$ROOT_DIR/cobe_code"
# ---
run_installer "$CODE_INSTALLER"
